// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `@graphql-tools/utils` might not be installed by user
import { printSchemaWithDirectives } from "@graphql-tools/utils";
import { type GraphQLSchema, lexicographicSortSchema, printSchema } from "graphql";
import { outputFile, outputFileSync } from "@/helpers/filesystem";

export interface PrintSchemaOptions {
  sortedSchema: boolean;
  includeDirectives: boolean;
}

export const defaultPrintSchemaOptions: PrintSchemaOptions = {
  sortedSchema: true,
  includeDirectives: false,
};

const generatedSchemaWarning = /* graphql */ `\
# -----------------------------------------------
# !!! THIS FILE WAS GENERATED BY TYPE-GRAPHQL !!!
# !!!   DO NOT MODIFY THIS FILE BY YOURSELF   !!!
# -----------------------------------------------

`;

function getSchemaFileContent(schema: GraphQLSchema, options: PrintSchemaOptions) {
  const schemaToEmit = options.sortedSchema ? lexicographicSortSchema(schema) : schema;
  const printedSchema = options.includeDirectives
    ? printSchemaWithDirectives(schemaToEmit)
    : printSchema(schemaToEmit);
  return generatedSchemaWarning + printedSchema;
}

export function emitSchemaDefinitionFileSync(
  schemaFilePath: string,
  schema: GraphQLSchema,
  options: PrintSchemaOptions = defaultPrintSchemaOptions,
) {
  const schemaFileContent = getSchemaFileContent(schema, options);
  outputFileSync(schemaFilePath, schemaFileContent);
}

export async function emitSchemaDefinitionFile(
  schemaFilePath: string,
  schema: GraphQLSchema,
  options: PrintSchemaOptions = defaultPrintSchemaOptions,
) {
  const schemaFileContent = getSchemaFileContent(schema, options);
  await outputFile(schemaFilePath, schemaFileContent);
}
